# fly.toml app configuration file generated for banca-movil-api on 2023-06-12T20:17:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "banca-movil-api"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
